apiVersion: v2
name: DriveBC-Image-Ingestion
description: DriveBC.ca Image Ingestion Service
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: frontend
    version: '0.1.0'
    repository: 'file://./charts/frontend'
    condition: frontend.enabled
  - name: backend
    version: '0.1.0'
    repository: 'file://./charts/backend'
    condition: backend.enabled