fullnameOverride: prod-image-ingestion-service
nameOverride: prod-image-ingestion-service

# These global values are used by all components of the application.
global:
  vault:
    licenceplate: f4dbc3 # This is the license plate you are deploying to. It is used to determine the vault path
    environment: prod #Set to prod if you want to use the prod vault or nonprod for dev/test/uat
  release: # This is set by Github actions for the prod release. Do not change this value.

frontend:
  replicaCount: 3 
  image:
    repository: ghcr.io/bcgov/drivebc.ca-images-frontend
    tag: latest
  deployment:
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 100Mi
    env:
      variables:
        ENVIRONMENT: prod
  route:
    host: prod-image-ingestion-service.apps.gold.devops.gov.bc.ca # Hostname for the route
    vanityurl: true #Set to true if you want to use a vanity URL. This will require a certificate in the cluster (set manually) and dns entry
    vanityurlhost: dbc-api.th.gov.bc.ca  #The path to use for the vanity URL
  podDisruptionBudget: 
    enabled: true # If you have more than 1 replica, you can set this to true.
    minAvailable: 1


backend:
  replicaCount: 3
  image:
    repository: ghcr.io/bcgov/drivebc.ca-images-backend
    tag: latest
  deployment:
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 250Mi
    env:
      variables:
        PYTHON_LOG_LEVEL: INFO
  vault:
    secretName: prod-image-ingestion  # This is the name of the secret in vault that contains the environment variables for the app
    authPath: auth/k8s-gold # Must match cluster. Use one of: k8s-silver, k8s-gold, k8s-golddr, k8s-emerald


  podDisruptionBudget: 
    enabled: true # If you have more than 1 replica, you can set this to true.
    minAvailable: 1