fullnameOverride: dev-image-ingestion-service
nameOverride: dev-image-ingestion-service


frontend:
  replicaCount: 1 
  image:
    repository: ghcr.io/bcgov/drivebc.ca-images-frontend
    tag: latest
  deployment:
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 100Mi
    env:
      variables:
        ENVIRONMENT: dev
  route:
    host: dev-image-ingestion-service.apps.gold.devops.gov.bc.ca # Hostname for the route
  podDisruptionBudget: 
    enabled: false # If you have more than 1 replica, you can set this to true.
    minAvailable: 1


backend:
  replicaCount: 1
  image:
    repository: ghcr.io/bcgov/drivebc.ca-images-backend
    tag: latest
  deployment:
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 100Mi
  podDisruptionBudget: 
    enabled: false # If you have more than 1 replica, you can set this to true.
    minAvailable: 1