
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}
  labels: {{ include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 8 }}
  template:
    metadata:
      labels:
        {{ include "app.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/port: '8000' 
        prometheus.io/scrape: 'true'  
        prometheus.io/path: "/api/metrics"
    spec:
      containers:
        - name: {{ template "app.fullname" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8000
              protocol: TCP
          envFrom:
          - secretRef: 
              name: {{ template "app.fullname" . }}
          resources:
            requests:
              cpu: {{ .Values.deployment.resources.requests.cpu }}
              memory: {{ .Values.deployment.resources.requests.memory }}
            limits:
              memory: {{ .Values.deployment.resources.limits.memory }}
