# Temporary, will eventually be moved to Vault
{{- if not (lookup "v1" "Secret" .Release.Namespace (include "app.fullname" .)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}
  labels: {{ include "app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
    DB_SERVER: 
    FTP_HOST: 
    RABBITMQ_EXCHANGE_NAME: 
    FTP_USER: 
    LOCATION_USER_PASS_MAPPING: 
    DB_NAME: 
    DB_USER: 
    RABBITMQ_URL: 
    FTP_PASS: 
    CAMERA_IP_MAPPING: 
    DB_PASSWORD: 
    FTP_TARGET_DIR: 
    FTP_PORT: 
    CAMERA_LOCATION_MAPPING: 
{{- end }}