services:
  image-receiver:
    container_name: image-receiver
    build: ./image_receiver
    ports:
      - "8000:8000"
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
      - LOCATION_USER_PASS_MAPPING=${LOCATION_USER_PASS_MAPPING}
      - FTP_HOST=${FTP_HOST}
      - FTP_PORT=${FTP_PORT}
      - FTP_USER_NAME=${FTP_USER}
      - FTP_USER_PASS=${FTP_PASS}
      - FTP_USER_HOME=/home/test
      - DB_SERVER=${DB_SERVER}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}