name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  code-quality: write

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/image_ingestion_service/image_receiver

    steps:
      - name: Checkout source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: "3.14"

      - name: Install ODBC Driver 18
        run: |
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18 unixodbc-dev

      - name: Install Python dependencies
        run: "python -m pip install --require-hashes --no-cache-dir --only-binary :all: -r requirements-dev.txt"

      - name: Run unit tests
        run: |
          python -m pytest -v \
            --cov=app \
            --cov-report=term-missing \
            --cov-report=markdown-append:$GITHUB_STEP_SUMMARY \
            --cov-report=xml:coverage.xml

      - name: Upload coverage report to GitHub
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/upload-code-coverage@2b21a77928be8d5168c2b9581a67f2adbebacc52 # v1
        with:
          file: src/image_ingestion_service/image_receiver/coverage.xml
          language: Python
          label: code-coverage/pytest
